# Ah 7th Variables Practice
name="Arthur"
print(name)
number_1="5"
print(number_1)
number_2="325"
print(number_2)
brecfest="cereal"
print(brecfest)
coler="blue"
print(coler)
scool="ucas"
print(scool)
year="2025"
print(year)
coler="brown"
print(coler)
age="15"
print(age)
subject="science"
print(subject)
print(subject)